name: 'Build, test, deploy'
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 'Build'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Setup Dependencies
        run: |
          corepack enable
          npm install
      - name: Build App and Typedoc
        run: |
          npm run build
          npm run typedoc
      # https://github.com/actions/upload-pages-artifact
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs
      - name: Deploy Typedoc to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v2

  test:
    name: 'Test'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Setup Dependencies
        run: |
          corepack enable
          npm install
      - name: Jest Tests
        env:
          CHINOOK_DATABASE_URL: ${{ secrets.CHINOOK_DATABASE_URL }}
          TESTING_DATABASE_URL: ${{ secrets.TESTING_DATABASE_URL }}
          GATEWAY_URL: ${{ secrets.GATEWAY_URL }}
        run: npm test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
