name: Publish TypeDoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Generate TypeDoc Documentation
      run: npm run typedoc

    - name: Deploy to GitHub Pages
      uses: name: Publish TypeDoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set your Node.js version here

    - name: Install Dependencies
      run: npm install

    - name: Generate TypeDoc Documentation
      run: npm run typedoc  # Replace with your TypeDoc script

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        branch: gh-pages  # Pushes to the gh-pages branch
        folder: docs      # Replace with the folder where TypeDoc outputs the files

      with:
        branch: gh-pages  # Pushes to the gh-pages branch
        folder: docs      # Replace with the folder where TypeDoc outputs the files
