name: 'CI/CD Tests'
on: push

jobs:
  app-tests:
    name: 'Package Tests'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup Dependencies
        run: |
          corepack enable
          npm install

      - name: Build App
        run: npm run build
        continue-on-error: true

      - name: Jest Tests
        env:
          CHINOOK_DATABASE_URL: ${{ secrets.CHINOOK_DATABASE_URL }}
          TESTING_DATABASE_URL: ${{ secrets.TESTING_DATABASE_URL }}
        run: npm test

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
